### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by modernstar** [bluecabin/Textoo#1]
Here is the log
05-18 11:02:34.318 14181-14181/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.moxin.android, PID: 14181
                                                   java.lang.NoClassDefFoundError: scala.collection.immutable.Queue$
                                                       at org.bluecabin.textoo.impl.TextViewConfiguratorImpl$.create(TextViewConfiguratorImpl.scala:87)
                                                       at org.bluecabin.textoo.impl.TextViewConfiguratorImpl.create(TextViewConfiguratorImpl.scala)
                                                       at org.bluecabin.textoo.ConfiguratorFactory.createTextViewConfigurator(ConfiguratorFactory.java:32)
                                                       at org.bluecabin.textoo.Textoo.config(Textoo.java:25)
                                                       at com.moxin.android.SignUpActivity.onCreate(SignUpActivity.java:25)
                                                       at android.app.Activity.performCreate(Activity.java:5245)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5052)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by phleemac** [comment]
Likely that the class `scala.collection.immutable.Queue$` got removed by proguard in your build.  Check your proguard config and add the necessary `-keep` configs.  Attached below is a working proguard config for your reference.  You might need to tailor it to fit your project:

`proguard-rules.pro`:

<pre>
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /home/fergus/Development/android-sdk-linux/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html
# Add any project specific keep options here:
# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}
###
# Scala proguard config
###
-dontnote scala.ScalaObject
-dontnote org.xml.sax.EntityResolver
-dontnote scala.concurrent.forkjoin.**
-dontwarn scala.beans.ScalaBeanInfo
-dontwarn scala.concurrent.**
-dontnote scala.reflect.**
-dontwarn scala.reflect.**
-dontwarn scala.sys.process.package$
-dontwarn **$$anonfun$*
-dontwarn scala.collection.immutable.RedBlack$Empty
-dontwarn scala.tools.**,plugintemplate.**
-keep public class scala.reflect.ScalaSignature
# This is gone in 2.11
-keep public interface scala.ScalaObject
-keepclassmembers class * {
    ** MODULE$;
}
-keep class scala.collection.SeqLike {
    public java.lang.String toString();
}
-keepclassmembernames class scala.concurrent.forkjoin.ForkJoinPool {
    long eventCount;
    int  workerCounts;
    int  runControl;
    scala.concurrent.forkjoin.ForkJoinPool$WaitQueueNode syncStack;
    scala.concurrent.forkjoin.ForkJoinPool$WaitQueueNode spareStack;
}
-keepclassmembernames class scala.concurrent.forkjoin.ForkJoinWorkerThread {
    int base;
    int sp;
    int runState;
}
-keepclassmembernames class scala.concurrent.forkjoin.ForkJoinTask {
    int status;
}
-keepclassmembernames class scala.concurrent.forkjoin.LinkedTransferQueue {
    scala.concurrent.forkjoin.LinkedTransferQueue$PaddedAtomicReference head;
    scala.concurrent.forkjoin.LinkedTransferQueue$PaddedAtomicReference tail;
    scala.concurrent.forkjoin.LinkedTransferQueue$PaddedAtomicReference cleanMe;
}
###
# Project config
###
-keepclassmembers class scala.Option { public *; }
-keepclassmembers class scala.Predef* { public *; }
-keepclassmembers class scala.Tuple* { public *; }
-keepclassmembers class scala.runtime.VolatileObjectRef { public *; }
-keepclassmembers class scala.collection.immutable.Range* { public *; }
-keepclassmembers class scala.concurrent.ExecutionContext* { public *; }
-keepclassmembers class scala.concurrent.duration.package$* { public *; }
-keepclassmembers class scala.concurrent.Future* { public *; }
-keepclassmembers class scala.collection.JavaConverters* { public *; }
-keepclassmembers class scala.collection.mutable.Set* { public *; }
-keepclassmembers class scala.collection.Seq* { public *; }
# Android Support Libs
-keep,includedescriptorclasses class android.support.v7.widget.SearchView { *; }
# Google Play Services
-keep,includedescriptorclasses class com.google.android.gms.**
# Glide
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
    **[] $VALUES;
    public *;
}
</pre>
